import { useWalkthrough } from '@/contexts/WalkthroughContext';
import Brand from "@/components/Brand";
import type { AnchorHTMLAttributes } from "react";
import { useEffect, useRef, useState } from 'react';
import { ArrowUpRight, ArrowRight, ChevronDown, X, Menu, FileCheck2, BadgeCheck, CalendarDays, GraduationCap, Activity, MessageCircle } from 'lucide-react';
import '@/home-refinement.css';
const portal='';
const services=[
 ['01',FileCheck2,'Credential verification','DataFlow, primary source verification and document authentication.','Verification'],
 ['02',BadgeCheck,'Professional licensing','Support with DHA, SCFHS, NHRA and DOH licensing applications.','Licensing'],
 ['03',CalendarDays,'Exam booking','Scheduling and preparation support for your next professional exam.','Exams'],
 ['04',GraduationCap,'Academic evaluation','Guidance with transcript assessment and international credential recognition.','Evaluation'],
 ['05',Activity,'Application tracking','Your current stage, received documents and next steps, together.','Tracking'],
 ['06',MessageCircle,'Personal support','Reach the team by WhatsApp, email or a scheduled conversation.','Support'],
] as const;
const faq=[
 ['How do I get access to the portal?','Existing clients can activate their account using the case reference and email address in their ELAB welcome email. If you do not have a case reference, contact the team to get started.'],
 ['How long does verification take?','The current ELAB service guidance gives a typical range of two to four weeks. Timing varies by service and the responsiveness of source institutions. Ask your case manager about your application.'],
 ['Which documents will I need?','Requirements depend on the service and authority. They may include a passport, professional license, degree certificate and academic transcript. Check your case requirements before uploading anything.'],
 ['How can I track my application?','Sign in to view your application’s current stage, timeline and document information. The portal also provides access to support when you need clarification.'],
 ['What if I already sent my documents?','Check the documents on file for your application first. You do not need to upload a second copy unless the team asks you to provide one.'],
 ['What if my application is rejected?','Contact your case manager to discuss the reason and the next available steps. Options depend on the service and the relevant authority.'],
];
function Out({href,children,...props}: AnchorHTMLAttributes<HTMLAnchorElement>){return <a href={href} {...props}>{children}</a>;}
export default function Homepage(){
 const { startTour } = useWalkthrough();
 function tour(){startTour({id:'homepage-overview',name:'Using the ELAB portal',steps:[
  {id:'account',target:'.client-access',title:'Access your account',content:'Sign in to an existing account or activate it using your welcome email reference.',placement:'left'},
  {id:'services',target:'#services',title:'Find a service',content:'Explore licensing, verification and exam services. Contact the team for help choosing.',placement:'top'},
  {id:'process',target:'#how-it-works',title:'Follow your application',content:'Your portal keeps the current stage, documents and case updates available after sign-in.',placement:'top'},
  {id:'help',target:'#questions',title:'Get help',content:'Read common questions or contact the team about your application.',placement:'top'}
 ]});}

 const [menu,setMenu]=useState(false),[start,setStart]=useState(false);const dialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{document.title='ELAB · Healthcare licensing & verification';},[]);
 useEffect(()=>{if(start)dialog.current?.showModal();},[start]);
 return <div className="public-home">
 <a className="home-skip" href="#home-main">Skip to content</a>
 <header className="home-header"><a className="home-brand" href="/"><Brand/></a><nav aria-label="Homepage navigation" className={menu?'is-open':''}><a href="#services" onClick={()=>setMenu(false)}>Services</a><a href="#how-it-works" onClick={()=>setMenu(false)}>How it works</a><a href="#questions" onClick={()=>setMenu(false)}>FAQs</a><Out href={`${portal}/tools`}>Free tools<ArrowUpRight size={13}/></Out></nav><div className="home-header-actions"><Out href="/login">Sign in</Out><button className="home-button dark" onClick={()=>setStart(true)}>Get started<ArrowUpRight size={15}/></button><button className="home-menu" aria-label="Toggle navigation" aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X size={22}/>:<Menu size={22}/>}</button></div></header>
 <main id="home-main">
 <section className="portal-intro"><div className="home-wrap intro-grid"><div className="intro-copy"><p className="intro-label">ELAB SOLUTIONS INTERNATIONAL</p><h1>Healthcare licensing<br/>and verification.<br/><em>Handled with care.</em></h1><p>We help healthcare professionals prepare their documents, apply for licensing and follow their case through to the next stage.</p><a href="#services" className="intro-services">Find the service you need<ArrowRight size={18}/></a></div><aside className="client-access"><p className="access-label">CLIENT PORTAL</p><h2>Here to check <br/>your application?</h2><p>Sign in to see your current stage, documents and messages from the team.</p><a href="/login" className="home-button dark">Sign in to your account<ArrowRight size={17}/></a><div className="activate-account"><strong>First time signing in?</strong><p>Use the case reference in your welcome email to activate your account.</p><a href="/register">Activate account<ArrowRight size={15}/></a></div><a className="preview-access" href="/support">Help with your account<ArrowUpRight size={14}/></a></aside></div></section>
 <div className="home-wrap enquiry-strip"><p><strong>New to ELAB?</strong> Tell us where you want to practise. We’ll help you work out what’s needed.</p><button onClick={()=>setStart(true)}>Make an enquiry<ArrowUpRight size={17}/></button></div>
 <section className="home-services home-wrap" id="services"><div className="home-section-heading"><div><p className="section-kicker">Our services</p><h2>What can we help with?</h2></div><p>Choose a service to contact the team, or sign in to track an existing application.</p></div><div className="home-service-grid">{services.map(([n,,title,copy])=><a href={title==='Application tracking'?'/dashboard':`${portal}/support`} className="home-service" key={n}><h3>{title}</h3><p>{copy}</p><ArrowUpRight size={20}/></a>)}</div><p className="service-coverage">Service enquiries include <strong>DataFlow · DHA · SCFHS · NHRA · DOH</strong></p></section>
 <section className="home-process" id="how-it-works"><div className="home-wrap"><div className="home-section-heading"><div><p className="section-kicker">Getting started</p><h2>From enquiry to application.</h2></div><p>You’ll have a case reference and a place to keep track of your application.</p></div><ol>{[['Connect with the team','Tell us your destination and the service you need. We’ll help you understand the requirements.'],['Activate your portal','Use the case reference in your welcome email to create your client account.'],['Share your documents','See what’s already on file and add any documents requested for your application.'],['Follow your progress','Check your stage, review updates and reach your case manager when you need support.']].map(([title,copy],i)=><li key={title}><span>{i+1}</span><h3>{title}</h3><p>{copy}</p></li>)}</ol></div></section>
 <section className="home-faq home-wrap" id="questions"><div><p className="section-kicker">Before you start</p><h2>Common questions.</h2><p>Need help with your own application?</p><a className="home-demo" href={`${portal}/support`}>Contact support<ArrowUpRight size={17}/></a></div><div>{faq.map(([q,a])=><details key={q}><summary>{q}<ChevronDown size={17}/></summary><p>{a}</p></details>)}</div></section>
 <section className="home-final"><div className="home-wrap"><div><h2>Not sure which service you need?</h2><p>Talk to the team before you start an application.</p></div><a href="https://wa.me/2348165634195" className="home-button dark">Message us on WhatsApp<ArrowUpRight size={17}/></a></div></section>
 </main>
 <footer className="home-wrap home-footer"><div className="home-footer-top"><div><a className="home-brand" href="/"><Brand/></a><p>Healthcare licensing<br/>and verification support.</p></div><div><h3>Explore</h3><a href="#services">Our services</a><a href="/dashboard">Client portal</a><button className="home-tour-link" onClick={tour}>Portal tour</button><a href="https://elabsolution.org/">ELAB & success stories</a><a href={`${portal}/tools`}>Free tools</a></div><div><h3>Support</h3><a href={`${portal}/support`}>Help & support</a><a href="/faq">All FAQs</a><a href={`${portal}/support/verification-fees`}>Verification fees</a><a href="/recruiter/register">Recruiter registration</a><a href="/contact/register">Institution registration</a></div><div><h3>Let’s talk</h3><a href="mailto:support@elabsolution.org">support@elabsolution.org</a><a href="https://wa.me/2348165634195">WhatsApp</a><a href="https://linkedin.com/company/elab-solutions-intl-llc/">LinkedIn</a><a href="https://x.com/elabsolution1">X / Twitter</a><a href="tel:+2348165634195">+234 816 563 4195</a><a href="tel:+19294192327">+1 (929) 419-2327</a></div></div><div className="home-office-addresses"><p>4, Addo Road, Suite 10, Stephen Taiwo Shopping Complex, Ajah, Lagos, Nigeria</p><p>828 Lane Allen Road 219, Lexington, Kentucky, USA</p></div><div className="home-footer-bottom"><span>© 2026 ELAB Solutions International.</span><div><a href={`${portal}/privacy`}>Privacy</a><a href={`${portal}/terms`}>Terms</a><a href={`${portal}/support/refund-policy`}>Refund policy</a><a href={`${portal}/privacy#cookies`}>Cookie settings</a></div></div></footer>
 {start&&<dialog ref={dialog} onCancel={()=>setStart(false)} onClick={e=>{if(e.target===dialog.current)setStart(false);}} aria-labelledby="start-heading"><div className="dialog-heading"><h2 id="start-heading">How can we help?</h2><button className="icon-button" aria-label="Close" onClick={()=>setStart(false)}><X size={22}/></button></div><p className="home-start-intro">Are you starting an enquiry or activating an existing case?</p><a className="home-start-option" href={`${portal}/support`}><div><strong>I’m new to ELAB</strong><span>Speak with the team about your service and requirements.</span></div><ArrowUpRight size={20}/></a><a className="home-start-option" href="/register"><div><strong>I have a case reference</strong><span>Activate your account using your welcome email.</span></div><ArrowUpRight size={20}/></a><p className="home-start-login">Already registered? <a href="/login">Sign in</a></p></dialog>}
 </div>;
}
